name: Build Android APK

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build Android APK
      run: |
        cd android
        gradlew assembleRelease

    - name: Save APK Artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: android/app/build/outputs/apk/release/app-release.apk
